name: Scheduled Auto Sign In

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  auto-sign-in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download release asset
        run: |
          URL="https://github.com/s-ssss/Endfield-Sign/releases/latest/download/Skland-Auto-Sign-In-v1.0.1-linux-x64"
          echo "Downloading: $URL"
          curl -L -f -A "Mozilla/5.0" -o sign-in-program "$URL"
          ls -lh sign-in-program
          file sign-in-program
          chmod +x ./sign-in-program

      - name: Run sign-in program
        env:
          USER_TOKENS: ${{ secrets.USER_TOKENS }}
        run: |
          echo "$USER_TOKENS" > user_tokens.txt
          ./sign-in-program
